### ISSUE TITLE
Proposal: Change enqueue interface

### ISSUE THREAD

**Issue by ono** [shinyscorpion/task_bunny#3]
I think that the current enqueue interface is bit confusing.

```elixir
TaskBunny.SyncPublisher.push(job_module, payload)
TaskBunny.SyncPublisher.push(SampleJob, %{"id" => 123123})
```

Here are problems...

- SyncPublisher is not an intuitive name
- It contains two different words for same meaning: publish and push
- The use of `Sync` is confusing. It is intended to indicate the message is sent to RabbitMQ synchronously but it might be misleading with the way it process a job

Here are some examples from popular background processing in Ruby.

```ruby
# Sidekiq
HardWorker.perform_async(payload)

# ActiveJob
HardWorker.perform_later(payload)

# Resque
Resque.enqueue(HardWorker, payload)
```

All them are clear and I prefer any to our existing interface. However since TaskBunny is not aiming to abstract background processing (because Erlang/Elixir already has it), I prefer to have a clarity that it enqueues a job (to RabbitMQ). Therefore I would suggest:

```elixir
TaskBunny.enqueue(Hardworker, payload)
or
HardWorker.enqueue(payload)
```

Any thoughts?

**Comment by ricardoperez** [comment]
I prefer the `Module.enqueue/1`

**Comment by ono** [comment]
Merged https://github.com/shinyscorpion/task_bunny/pull/14
