### ISSUE TITLE
[RFC] Add ability to define custom Job name for a module

### ISSUE THREAD

**Issue by PhillippOhlandt** [shinyscorpion/task_bunny#39]
Hey,

right now, the job name is the module name. In my case, I have a worker application and an extra application that pushes jobs into the queues. The current behaviour forces me to define the exact same module `Worker.Jobs.TestJob` in my API application. It would be really helpful if we could set a custom job name on the module.

Example:

```elixir
defmodule Worker.Jobs.TestJob do
  use TaskBunny.Job

  def job_name, do: "TestJob"

  def perform(%{"name" => name}) do
    :timer.sleep 1000
    IO.puts "Hello #{name}"
    :ok
  end
end
```

```elixir
defmodule Publisher.Jobs.TestJob do
  use TaskBunny.Job

  def job_name, do: "TestJob"

  def perform(_payload) do
    # no action
  end
end
```

What do you guys think?

**Comment by ono** [comment]
If the publisher is just a separate Elixir application you don't need to define `Worker.Jobs.TestJob` in publisher application. You can just do:

```elixir
TaskBunny.Job.enqueue!(Worker.Jobs.TestJob, %{"name" => "Taro})
```
`enqueue` takes `Worker.Jobs.TestJob` as atom.

**Comment by PhillippOhlandt** [comment]
Ah ok, so I don't even have to define a module then. That's nice. Thanks!

**Comment by PhillippOhlandt** [comment]
I just tried it. Seems like it doesn't work.

```
iex(1)> TaskBunny.Job.enqueue!(Worker.Jobs.TestJob2, %{"name" => "Taro"})
:ok

16:28:32.150 [error] TaskBunny.Worker: basic_deliver invalid body. Queue: video_search.normal. Concurrency: 1. PID: #PID<0.287.0>. [body: "{\n  \"payload\": {\n    \"name\": \"Taro\"\n  },\n  \"job\": \"Worker.Jobs.TestJob2\",\n  \"created_at\": \"2017-07-26T14:28:32.113663Z\"\n}", error: {:error, :job_not_loaded}]
```

**Comment by PhillippOhlandt** [comment]
Sorry, it's the worker process which errored because the module doesn't exist.
