### ISSUE TITLE
Jobs for third party message payloads

### ISSUE THREAD

**Issue by polmiro** [shinyscorpion/task_bunny#46]
One of the most powerful features from RabbitMQ is the concept of exchanges. Let's the system plug and play new queues and add new data pipelines and behaviors over time.

Since the library enqueues messages with a specific payload format (JSON structure with "job", "payload" and "created_at" keys) it is not possible to create a worker against a queue whose message payload is published from a different system. Is this something that you would like to consider for task_bunny? I would be happy to try to come up with a solution if you think this feature aligns with the project.

**Comment by ono** [comment]
Hi @polmiro. I agree that Exchange is a powerful feature. However TaskBunny is not general RabbitMQ wrapper. The aim of this project is to provide simple job queueing library like Resque, Sidekiq, RQ etc. in other languages.

I would be thrilled to see other libraries coming up different approaches and making use of power of RabbitMQ but it's beyond TaskBunny's project scope.

Hope it answers your question. Thanks!

**Comment by polmiro** [comment]
Alright 👍 . I'm still not fluent with elixir, if I were to find a nice way to hook this behavior I might come back to you. Thanks
