### ISSUE TITLE
How to process rejected jobs?

### ISSUE THREAD

**Issue by archSeer** [shinyscorpion/task_bunny#55]
We have a job that polls an external API for a condition to become true, if not, we fail and let the job retry. If the job fails all the retries, we'd like to process the failed job from the rejected queue and mark that request in the db as `error/timeout`. Is there an easy way to have a worker process the rejected jobs from a specific queue?

**Comment by ono** [comment]
As the requirements on rejected job varies TaskBunny doesn't provide any functionalities to access it. However it is easy to write a code that deals with the queue/messages.

```elixir
{:ok, conn} = TaskBunny.Connection.get_connection(:default)
{:ok, chan} = AMQP.Channel.open(conn)
case AMQP.Basic.get(chan, @reject_queue) do
  {:ok, message, meta} ->
    # found a rejected message (it has been popped by get)
    process_message(message)
  {:empty, _} ->
    # no rejected message
end
AMQP.Channel.close(chan)
```

It's just a sample code. You can extract the code around case statement and make it recursive to process all messages.

You can also write GenSever to listen the queue if you need more controlled way. There is a sample code [here](https://github.com/pma/amqp#setup-a-consumer-genserver) or you can check TaskBunny's worker implementation.

**Comment by archSeer** [comment]
Hi, but setting up a separate GenServer to process raw amqp messages seems a bit of an overkill, could we just somehow get the retry_count inside the worker? That way we could detect the last retry and mark the job as a fail:

```elixir
defmodule MyJob do
  use TaskBunny.Job

  @impl true
  def perform(%{"id" => id}) do
    if current_retry == max_retries do
      reject(id)
    else
      # normal operation
    end
  end

  defp reject(id) do
    # update my_model.id in database to state :timeout
  end
end


```

**Comment by ono** [comment]
`current_retry` wouldn't be accessible from `perform/1` unless we have `perform/2` which passes some option values like `retry_count`.

I would rather propose to support `reject` callback which would be called when the job is rejected.

**Comment by archSeer** [comment]
That would work for us! :) alternatively, you could define a `perform/2` with a `@defoverridable` default, so that it's backwards compatible

**Comment by kalymero** [comment]
@ono we are thinking the same thing here. Adding a callback for it would be cool (`reject`, `on_reject`, `on_failure` as possible names).

We may require it soon so if you don't plan to work on it  we may possibly try to PR it.  

Thoughts?

**Comment by kalymero** [comment]
https://github.com/shinyscorpion/task_bunny/pull/61/files

**Comment by kalymero** [comment]
@archSeer 0.3.3 has been released. You can now implement the `on_reject` callback:

```elixir
defmodule FlakyJob do
  use TaskBunny.Job

  def on_reject(_body) do
     ...

     :ok
  end
  ...
end
```

Closing this one
