### ISSUE TITLE
Repeating jobs on a set schedule

### ISSUE THREAD

**Issue by nickjj** [shinyscorpion/task_bunny#59]
Hi,

Thanks so much for making this library but I had a question.

Let's say I want to execute a job every day at 11pm (or any other interval such as every other Sunday). What would you recommend doing in this case?

Would you reach for a third party scheduling library like https://github.com/quantum-elixir/quantum-core to use in combination with task_bunny's jobs, or is this type of feature something that could be added to task_bunny directly?

**Comment by ono** [comment]
Good question ... and good answer 👍Yes, using library like quantum-core would be the solution. Adding the cron functionality to TaskBunny sounds overkill and those existing libraries seem to do the good job already.
